### ISSUE TITLE
SDK v3.4.0 not compatible with latest GuzzleHttp version

### ISSUE THREAD

**Issue by shockbytes** [talon-one/TalonOnePHPsdk#14]
Hi there!

We are experiencing a problem with your SDK. Our project has several dependencies that are using `GuzzleHttp` version 7.5.0. Internally, you are using already deprecated methods of `GuzzleHttp` as `build_query` (see https://github.com/talon-one/TalonOnePHPsdk/blob/master/lib/Api/IntegrationApi.php#L380). This method was removed from the library with the release of version 7.2. Therefore your integration is not working as `IntegrationApi` won't be able to resolve the method as it does not exist. 

Downgrading the version of `GuzzleHttp` is not an option for us, as this won't satisfy the dependencies of the other libraries. We were able to solve this locally by overriding the affected class and using `IntegrationApi` on a project-level (which isn't a really sustainable solution but a quick workaround until you updated your SDK).

Looking forward to hearing about the applied fix from you.

P.S.: Here are some links also describing this issue for other libraries:

https://devscope.io/code/sendinblue/APIv3-php-library/issues/165
https://github.com/doofinder/php-doofinder/issues/66

**Comment by shockbytes** [comment]
@joaopbnogueira I was already in contact with talon.one and they provided a fix in the version `3.6.0.x-dev`. We already use this version and it works.

**Comment by joaopbnogueira** [comment]
@shockbytes thanks for the heads up, I missed the 3.6 tag (was looking at the releases). Cheers.

**Comment by shockbytes** [comment]
You're welcome.

**Comment by altJake** [comment]
Hey all, 
Thanks for the mutual help here and apologies for our very big delay on this issue.
Like @shockbytes mentioned, we have created an ad-hoc branch with fixes to this guzzle issues (v3.6.0) and it was long usable to circumvent the guzzle changed-api issues.

I have finally found the time to make an official release to address this problem and gap. You can refer to the new [v4.0.0](https://github.com/talon-one/TalonOnePHPsdk/releases/tag/v4.0.0) major version.

The reason for choosing the major version bump is simply to reflect the change in the dependency version of Guzzle, I think it makes sense as it might impose certain changes of consumers of the library and force them to update their other dependencies in the project if they haven't done so before. 
However, if you already used the v3.6.0 (or even v3.5.0 dev branches) you should be able to bump to v4.0.0 with no code changes on your end!

@shockbytes @joaopbnogueira, please let me know when you give it a try and we can confirm this as fixed. Thank you for your help in improving this library!

**Comment by joaopbnogueira** [comment]
@altJake thanks, upgrade is looking fine so far!

**Comment by shockbytes** [comment]
Thanks @altJake we are updating it on our side and keep you posted.

**Comment by altJake** [comment]
Thank you both, I will go ahead and close it for now, if you see any problems with the new versions - please feel free to reopen this ticket or a new one, I will be happy to assist in resolving it!
